name: Haskell Windows

# Trigger the workflow on push or pull request, but only for the master branch
on:
  push:
    branches: [windows-test]
    # paths:
    # - 'languages/haskell/**'

jobs:

  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: windows-latest
    strategy:
      matrix:
        stack: ["2.3.1"]
        ghc: ["8.8.3"]

    steps:
    - uses: actions/checkout@v2
      # if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: actions/setup-haskell@v1.1
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack-${{ hashFiles('languages/haskell/stack.yaml') }}

    - name: Install dependencies
      run: |
        # stack update
        stack build --system-ghc --only-dependencies
      working-directory: languages/haskell

    - name: Build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
      working-directory: languages/haskell

    - name: Test
      run: |
        stack test --system-ghc
      working-directory: languages/haskell
